### ISSUE TITLE
Error when get logcat from huawei P9

### ISSUE THREAD

**Issue by willysys** [openstf/adbkit-logcat#6]
There is a error when I get logcat from huawei P9. seems adbkit can't handle the corner case with empty entry data,error details as follows:

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Unprocessable entry data ''
    at Binary._processEntry (/usr/lib/nodejs/npm/node_modules/lib/node_modules/stf/node_modules/adbkit-logcat/lib/logcat/parser/binary.js:77:26)
    at Binary.parse (/usr/lib/nodejs/npm/node_modules/lib/node_modules/stf/node_modules/adbkit-logcat/lib/logcat/parser/binary.js:54:14)
    at LineTransform.<anonymous> (/usr/lib/nodejs/npm/node_modules/lib/node_modules/stf/node_modules/adbkit-logcat/lib/logcat/reader.js:84:33)
    at emitOne (events.js:96:13)
    at LineTransform.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at LineTransform.Readable.push (_stream_readable.js:134:10)
    at LineTransform.Transform.push (_stream_transform.js:128:32)
    at LineTransform._transform (/usr/lib/nodejs/npm/node_modules/lib/node_modules/stf/node_modules/adbkit/lib/adb/linetransform.js:39:12)
    at LineTransform.Transform._read (_stream_transform.js:167:10)
    at LineTransform.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at LineTransform.Writable.write (_stream_writable.js:247:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)

**Comment by sorccu** [comment]
Have you tried turning the `fixLineFeeds` option off?

**Comment by willysys** [comment]
This error occurred during the STF run.

**Comment by willysys** [comment]
Maybe adbkit can't handle the corner case with empty entry data.

**Comment by sorccu** [comment]
Ok... well, run `adb logcat -B -d > adbkit-logcat-issue-8.log && gzip adbkit-logcat-issue-8.log`. Then send the newly created `adbkit-logcat-issue-8.log.gz` to simo @ {the name of this github org} .io or attach it here. Note that private information may be exposed in the log output. However, without having access to the output I can do nothing.

I will eventually look into the issue but don't expect a fix immediately, I'm super busy.

**Comment by Andychochocho** [comment]
@sorccu How do you set the fixLineFeeds option to be false? Getting this error on newer versions of Android and I can't figure out how to disable that feature.

**Comment by sorccu** [comment]
Show me how you've attempted to do it.

**Comment by Andychochocho** [comment]
I've tried looking through the logcat documentation for something to implement like a flag maybe I'm missing, but I can't seem to find anything like how there's the -B for the binary issue.

**Comment by Andychochocho** [comment]
@sorccu Is there a way you recommend going about this, or am I just missing something very obvious here? 😬

**Comment by histronger** [comment]
@willysys Seems the problem starts here, and do you have a solution already?
![image](https://user-images.githubusercontent.com/5714668/63751223-7d7c3680-c8e1-11e9-9aae-c40674160286.png)

**Comment by histronger** [comment]
@sorccu Can you help to have a look? Thanks!
